# Generated by Django 3.1.7 on 2021-06-24 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0002_auto_20210402_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=100)),
                ('sub_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('sub_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ablog.section')),
            ],
        ),
    ]
